name: SecScore PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  secscore:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # SecScore
    - name: Run SecScore
      uses: cassiodeveloper/secscore@v1
      with:
        sarif: results.sarif
