[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "secscore"
version = "0.4.0"
description = "Security score engine for CI/CD pipelines"
requires-python = ">=3.9"
authors = [{name="Cassio B. Pereira"}]

dependencies = [
    "pyyaml>=6.0",
    "requests>=2.31",
    "rich>=13.0.0"
]

[tool.setuptools.packages.find]
include = ["secscore*"]
