from __future__ import annotations

from typing import Any, Dict, List, Optional
from .engine import EngineResult

def _get(d: Dict[str, Any], path: str) -> Optional[Any]:
    cur: Any = d
    for part in path.split("."):
        if not isinstance(cur, dict) or part not in cur:
            return None
        cur = cur[part]
    return cur

def render_pr_comment(result: EngineResult) -> str:
    emoji = {"PASS": "✅", "REVIEW": "🟡", "FAIL": "⛔"}[result.decision]

    lines: List[str] = []
    lines.append(f"## SecScore {emoji}")
    lines.append(f"**Score:** `{result.score}/100`  \n**Decision:** `{result.decision}`")

    if result.reasons:
        lines.append("\n**Top reasons:**")
        for r in result.reasons:
            lines.append(f"- {r}")

    if result.findings_shown:
        lines.append("\n**Findings (new in this PR):**")
        for f in result.findings_shown:
            lines.append(_render_finding_line(f))

    lines.append("\n> Generated by SecScore — Security Score que importa.")
    return "\n".join(lines)

def _render_finding_line(f: Dict[str, Any]) -> str:
    title = f.get("title", "Untitled")
    sev = f.get("severity", "info").upper()
    dom = f.get("domain", "?").upper()

    path = _get(f, "asset.path")
    line = _get(f, "asset.line")
    cve = _get(f, "metadata.cve")
    pkg = _get(f, "metadata.package")
    img = _get(f, "metadata.image")

    loc = ""
    if path and line:
        loc = f" (`{path}:{line}`)"
    elif path:
        loc = f" (`{path}`)"

    extra = []
    if cve:
        extra.append(str(cve))
    if pkg:
        extra.append(str(pkg))
    if img:
        extra.append(str(img))

    extra_s = f" [{', '.join(extra)}]" if extra else ""
    return f"- **{dom}/{sev}**: {title}{loc}{extra_s}"